"""create tables

Revision ID: 62432d0cd182
Revises: 4bed3ca26487
Create Date: 2022-11-10 13:06:29.638993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62432d0cd182'
down_revision = '4bed3ca26487'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
   pass
    # ### end Alembic commands ###
