"""update tables

Revision ID: 93ae2477e083
Revises: 62432d0cd182
Create Date: 2022-11-12 16:02:13.791576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93ae2477e083'
down_revision = '62432d0cd182'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
